// Donna's — Catalog, content, copy

window.DONNA = window.DONNA || {};

window.DONNA.collections = [
  { id: 'tumblers',   name: 'Drinkware',          count: 24, kicker: 'Made to take with you' },
  { id: 'boards',     name: 'Boards & Servingware', count: 18, kicker: 'For the table you set' },
  { id: 'home',       name: 'Home & Keepsakes',   count: 32, kicker: 'Pieces that stay with you' },
  { id: 'accessories', name: 'Wallets & Accessories', count: 21, kicker: 'Everyday, made personal' },
  { id: 'wedding',    name: 'Wedding & Anniversary', count: 14, kicker: 'For the milestone moments' },
  { id: 'corporate',  name: 'Corporate & Bulk',   count: 8,  kicker: 'Gifts at scale' },
];

window.DONNA.products = [
  {
    id: 'p-skinny-tumbler',
    name: 'The Skinny Tumbler',
    sub: 'Engraved, 20 oz, double-wall',
    price: 38, msrp: 44,
    collection: 'tumblers',
    swatches: ['#E8E0D2', '#1F1410', '#B9533A', '#3D5848', '#C8985A'],
    swatchNames: ['Bone', 'Onyx', 'Terracotta', 'Forest', 'Brass'],
    tag: 'Best Seller',
    blurb: 'Slim, balanced, fits in a cup holder. Etched to last.',
    rating: 4.9, reviews: 318,
    type: 'tumbler',
  },
  {
    id: 'p-walnut-board',
    name: 'Walnut Serving Board',
    sub: 'Solid black walnut, hand-finished',
    price: 84, msrp: 96,
    collection: 'boards',
    swatches: ['#5A3823', '#3E2517'],
    swatchNames: ['Walnut', 'Espresso'],
    tag: 'New',
    blurb: 'Long-grain walnut with a juice groove and a finger pull.',
    rating: 5.0, reviews: 142,
    type: 'board',
  },
  {
    id: 'p-bourbon-decanter',
    name: 'Bourbon Decanter Set',
    sub: 'Lead-free crystal, monogrammed',
    price: 148,
    collection: 'home',
    swatches: ['#1F1410'],
    swatchNames: ['Crystal'],
    tag: 'Gift Set',
    blurb: 'Decanter, two rocks glasses, and a walnut base.',
    rating: 4.8, reviews: 87,
    type: 'decanter',
  },
  {
    id: 'p-leather-wallet',
    name: 'Bifold Leather Wallet',
    sub: 'Full-grain, vegetable-tanned',
    price: 72,
    collection: 'accessories',
    swatches: ['#3E2517', '#1F1410', '#7A4524'],
    swatchNames: ['Cognac', 'Onyx', 'Chestnut'],
    tag: 'Customer Favorite',
    blurb: 'Slim profile, six card slots, full bill pocket.',
    rating: 4.9, reviews: 211,
    type: 'wallet',
  },
  {
    id: 'p-oak-keepsake',
    name: 'Oak Keepsake Box',
    sub: 'Soft-close lid, velvet lined',
    price: 96,
    collection: 'home',
    swatches: ['#C8985A', '#3D5848'],
    swatchNames: ['Honey', 'Forest velvet'],
    tag: '',
    blurb: 'A box that holds the things you mean to keep.',
    rating: 4.9, reviews: 64,
    type: 'box',
  },
  {
    id: 'p-stanley-style',
    name: 'The 40oz Travel Cup',
    sub: 'Powder coat, straw lid, handle',
    price: 52,
    collection: 'tumblers',
    swatches: ['#B9533A', '#E8E0D2', '#3D5848', '#1F1410', '#7A4524'],
    swatchNames: ['Terracotta', 'Bone', 'Forest', 'Onyx', 'Caramel'],
    tag: 'Trending',
    blurb: 'Your daily cup. Fits a car cup holder.',
    rating: 4.9, reviews: 502,
    type: 'tumbler-tall',
  },
  {
    id: 'p-charcuterie',
    name: 'The Round Charcuterie',
    sub: 'Acacia round with handle',
    price: 64,
    collection: 'boards',
    swatches: ['#A5754B'],
    swatchNames: ['Acacia'],
    tag: '',
    blurb: '14-inch round, perfect for gatherings of six to eight.',
    rating: 4.9, reviews: 178,
    type: 'board-round',
  },
  {
    id: 'p-wine-set',
    name: 'Stemless Wine Set',
    sub: 'Set of four, etched glass',
    price: 88,
    collection: 'home',
    swatches: ['#E8E0D2'],
    swatchNames: ['Clear'],
    tag: 'Gift Set',
    blurb: 'Four stemless glasses in a giftable kraft box.',
    rating: 4.8, reviews: 96,
    type: 'glass',
  },
  {
    id: 'p-mini-board',
    name: 'Personal Cheese Board',
    sub: '8-inch walnut, gift-ready',
    price: 38,
    collection: 'boards',
    swatches: ['#5A3823'],
    swatchNames: ['Walnut'],
    tag: 'Under $50',
    blurb: 'Single-serve, perfect for hostess and housewarming gifts.',
    rating: 4.9, reviews: 234,
    type: 'board',
  },
];

window.DONNA.testimonials = [
  {
    quote: "I cried when I opened my mom's anniversary box. Donna engraved my parents' first dance lyrics around the lid and it's the most thoughtful gift I've ever given.",
    name: 'Imani K.',
    role: 'Atlanta, GA · Anniversary gift',
    rating: 5,
  },
  {
    quote: "We ordered 80 monogrammed tumblers for our bridesmaids and corporate gifts and Donna handled every single one personally. Real human, real craft.",
    name: 'Sydney & Marcus',
    role: 'Brooklyn, NY · Wedding party',
    rating: 5,
  },
  {
    quote: "I run a salon and we hand these tumblers out to clients on their first visit. They post them every time. Best marketing I've ever paid for.",
    name: 'Tasha B.',
    role: 'Houston, TX · Repeat customer',
    rating: 5,
  },
  {
    quote: "Donna designed a charcuterie board with our family tree etched into the back. It sits at every Sunday dinner. Generational.",
    name: 'The Whitfield Family',
    role: 'Charlotte, NC · Custom commission',
    rating: 5,
  },
];

window.DONNA.lifestyleScenes = [
  { id: 'ls-hike',     caption: 'Brielle on the Blue Ridge — Travel Cup in Terracotta', tag: 'TUMBLERS' },
  { id: 'ls-board',    caption: 'Sunday dinner at the Whitfields — engraved walnut board', tag: 'BOARDS' },
  { id: 'ls-bride',    caption: "Sydney's bridal suite — monogrammed flute set", tag: 'WEDDING' },
  { id: 'ls-studio',   caption: 'Donna at the laser — the moment before the first pass', tag: 'STUDIO' },
  { id: 'ls-wallet',   caption: 'A wallet engraved for a graduating son', tag: 'ACCESSORIES' },
  { id: 'ls-decanter', caption: "Father's Day, second pour", tag: 'HOME' },
];

window.DONNA.faqs = [
  { q: 'How does personalization work?',
    a: 'On every product page, you\'ll see a "Make it yours" panel. Type your text, choose a font and a placement, and watch a live preview update in real time. Want something more complex — a family crest, a hand-drawn sketch, a logo? Send a custom request and Donna replies within 24 hours.' },
  { q: 'How long does an order take?',
    a: 'Stock pieces with personalization ship in 3–5 business days. Fully custom commissions take 2–3 weeks depending on scope. Holiday and wedding rushes — talk to me directly and we\'ll work it out.' },
  { q: 'Can I see a proof before you engrave?',
    a: 'For custom commissions over $100 and any monogrammed bulk order (10+), you\'ll receive a digital proof within 48 hours. I don\'t touch the laser until you sign off.' },
  { q: 'Do you ship outside the US?',
    a: 'Yes — to Canada, the UK, the EU, and a growing list of countries. Shipping calculates at checkout. Wood and glass items are insured.' },
  { q: 'Returns and exchanges?',
    a: 'Stock items can be returned within 30 days, unused, in original packaging. Personalized or custom items can\'t be returned (they\'re made for you), but if there\'s a defect or I made a mistake, I make it right — no questions.' },
  { q: 'Can you do corporate or bulk orders?',
    a: 'Yes, and I love them. Branded tumblers for new hires, monogrammed boards for client gifts, wedding party sets of 20+ — fill out the corporate inquiry form or email me directly.' },
  { q: 'What materials do you work with?',
    a: 'Black walnut, white oak, acacia, leather (full-grain, vegetable-tanned), powder-coated steel tumblers, lead-free crystal, ceramic, and select metals. I source small and U.S.-first whenever I can.' },
  { q: 'Do you offer gift wrapping?',
    a: 'Every order ships in kraft and twine with a hand-written card at no charge. Add a velvet pouch or wooden gift box for $8 at checkout.' },
];

window.DONNA.engravingFonts = [
  { id: 'fraunces', label: 'Editorial Serif', css: "'Fraunces', serif", italic: false, weight: 500 },
  { id: 'fraunces-italic', label: 'Italic Script', css: "'Fraunces', serif", italic: true,  weight: 400 },
  { id: 'monogram', label: 'Monogram', css: "'Cormorant Garamond', 'Fraunces', serif", italic: false, weight: 600, monogram: true },
  { id: 'block',    label: 'Block Caps', css: "'Inter', sans-serif", italic: false, weight: 800, caps: true },
  { id: 'sans',     label: 'Modern Sans', css: "'Inter', sans-serif", italic: false, weight: 500 },
];

window.DONNA.engravingStyles = [
  { id: 'etch',   label: 'Etched',   desc: 'Light surface scoring, subtle and soft.' },
  { id: 'deep',   label: 'Deep cut', desc: 'Burned-through, high contrast.' },
  { id: 'fill',   label: 'Filled',   desc: 'Engraved and color-filled in brass or white.' },
];

window.DONNA.policies = [
  {
    id: 'shipping',
    title: 'Shipping',
    intro: 'How fast, how it\'s packed, how to track it.',
    sections: [
      { h: 'Processing time',
        p: 'Stock items with personalization: 3–5 business days. Made-to-order and commissions: 2–3 weeks. You\'ll see your specific lead time on the product page and confirmed in your order email.' },
      { h: 'Carriers and rates',
        p: 'USPS Priority for small parcels, UPS Ground for boards and decanter sets, FedEx for international. Rates calculate live at checkout. Free shipping on US orders over $125.' },
      { h: 'How it\'s packed',
        p: 'Recycled kraft, biodegradable cushion, twine, and a hand-written card. Wood and glass pieces ship in molded paper pulp inside double-walled cartons.' },
      { h: 'Tracking and insurance',
        p: 'Every order ships tracked. Fragile pieces (glass, decanters, ceramic) ship insured by default. If something arrives damaged, send photos within 48 hours and I\'ll replace it.' },
    ],
  },
  {
    id: 'returns',
    title: 'Returns & Refunds',
    intro: 'The fair version, not the long version.',
    sections: [
      { h: 'Stock items',
        p: 'Unused, in original packaging — return within 30 days for a full refund minus return shipping. Email hello@donnas.co for a return label.' },
      { h: 'Personalized & custom',
        p: 'Personalized items can\'t be returned — they\'re made for you. If I made a mistake (wrong spelling, wrong placement, defect), I replace it free. No questions, no proof needed.' },
      { h: 'Damaged in transit',
        p: 'Photos within 48 hours of delivery — I\'ll replace it, no return needed. Insured carriers reimburse me, not you.' },
      { h: 'Gift returns',
        p: 'Recipient can exchange unpersonalized stock pieces for store credit without involving the gift-giver.' },
    ],
  },
  {
    id: 'custom',
    title: 'Custom Order Policy',
    intro: 'How commissions and bulk orders work.',
    sections: [
      { h: 'How to start',
        p: 'Use the custom request form, email a brief, or DM on Instagram. Include: what the gift is for, recipient, deadline, budget, and any imagery or text.' },
      { h: 'Quote and timeline',
        p: 'I respond within 24 hours with a quote and timeline. Quotes are valid for 14 days. 50% deposit reserves your slot in the studio queue.' },
      { h: 'Proofs and revisions',
        p: 'Two rounds of revisions included. Additional rounds are $25 each. I won\'t engrave until you sign off — protect both of us.' },
      { h: 'Rush orders',
        p: 'Rushes available for an additional 25% depending on studio load. Ask before assuming — sometimes I have capacity, sometimes I genuinely don\'t.' },
      { h: 'IP and originality',
        p: 'You own what you commission. I keep a low-res photo for portfolio unless you ask me not to. I won\'t reuse your design.' },
    ],
  },
];
